export const competitions = [
    {
      slug: "toyota-corolla",
      title: "Win a Toyota Corolla + ₦2,000,000 Cash",
      category: "Cars",
      icon: "🚗",
      image: "/images/toyota-corolla.png",
      gradient: "from-[#052E24] via-[#0B4A3A] to-[#D6A84F]",
      price: "₦1,000",
      ticketPrice: 1000,
      drawDate: "30 June 2026",
      shortDrawDate: "30 June",
      sold: "62%",
      maxEntries: 20000,
      entriesSold: 12400,
      entriesText: "12,400 / 20,000",
      description:
        "Enter for a chance to win a Toyota Corolla plus ₦2,000,000 cash. This prize is designed for Nigerian users who want a reliable car and extra cash support.",
      highlights: [
        "Toyota Corolla prize package",
        "₦2,000,000 cash bonus",
        "Secure local payment options",
        "Transparent winner announcement",
        "Nigeria-wide participation",
      ],
    },
    {
      slug: "cash-prize",
      title: "Win ₦5,000,000 Cash Prize",
      category: "Cash",
      icon: "💰",
      image: "/images/cash-prize.png",
      gradient: "from-[#111827] via-[#052E24] to-[#D6A84F]",
      price: "₦500",
      ticketPrice: 500,
      drawDate: "15 July 2026",
      shortDrawDate: "15 July",
      sold: "48%",
      maxEntries: 20000,
      entriesSold: 9600,
      entriesText: "9,600 / 20,000",
      description:
        "Enter for a chance to win ₦5,000,000 cash. This prize can support rent, business, family needs or personal goals.",
      highlights: [
        "₦5,000,000 cash prize",
        "Affordable ticket price",
        "Secure local payment options",
        "Transparent winner announcement",
        "Nigeria-wide participation",
      ],
    },
    {
      slug: "iphone-16-pro-max",
      title: "Win an iPhone 16 Pro Max + ₦500,000",
      category: "Gadgets",
      icon: "📱",
      image: "/images/iphone-16-pro-max.png",
      gradient: "from-[#1E1B4B] via-[#312E81] to-[#D6A84F]",
      price: "₦300",
      ticketPrice: 300,
      drawDate: "10 July 2026",
      shortDrawDate: "10 July",
      sold: "71%",
      maxEntries: 10000,
      entriesSold: 7100,
      entriesText: "7,100 / 10,000",
      description:
        "Enter for a chance to win an iPhone 16 Pro Max plus ₦500,000 cash support.",
      highlights: [
        "iPhone 16 Pro Max",
        "₦500,000 cash bonus",
        "Low ticket price",
        "Transparent winner announcement",
        "Nigeria-wide participation",
      ],
    },
    {
      slug: "solar-inverter-package",
      title: "Win a Solar Inverter Package",
      category: "Lifestyle",
      icon: "☀️",
      image: "/images/solar-inverter.png",
      gradient: "from-[#78350F] via-[#92400E] to-[#D6A84F]",
      price: "₦700",
      ticketPrice: 700,
      drawDate: "20 July 2026",
      shortDrawDate: "20 July",
      sold: "35%",
      maxEntries: 10000,
      entriesSold: 3500,
      entriesText: "3,500 / 10,000",
      description:
        "Enter for a chance to win a solar inverter package suitable for Nigerian homes and small businesses.",
      highlights: [
        "Solar inverter package",
        "Useful for homes and businesses",
        "Secure local payment options",
        "Transparent winner announcement",
        "Nigeria-wide participation",
      ],
    },
    {
      slug: "delivery-bike-business-cash",
      title: "Win a Delivery Bike + ₦500,000 Business Cash",
      category: "Business",
      icon: "🏍️",
      image: "/images/delivery-bike.png",
      gradient: "from-[#7F1D1D] via-[#991B1B] to-[#D6A84F]",
      price: "₦500",
      ticketPrice: 500,
      drawDate: "25 July 2026",
      shortDrawDate: "25 July",
      sold: "54%",
      maxEntries: 10000,
      entriesSold: 5400,
      entriesText: "5,400 / 10,000",
      description:
        "Enter for a chance to win a delivery bike plus ₦500,000 business support cash.",
      highlights: [
        "Delivery bike prize",
        "₦500,000 business cash",
        "Useful for logistics or side business",
        "Transparent winner announcement",
        "Nigeria-wide participation",
      ],
    },
    {
      slug: "free-entry-cash",
      title: "Win ₦1,000,000 Free Entry Competition",
      category: "Free Entry",
      icon: "🎁",
      image: "/images/free-entry-cash.png",
      gradient: "from-[#064E3B] via-[#065F46] to-[#D6A84F]",
      price: "Free",
      ticketPrice: 0,
      drawDate: "5 August 2026",
      shortDrawDate: "5 August",
      sold: "22%",
      maxEntries: 10000,
      entriesSold: 2200,
      entriesText: "2,200 / 10,000",
      description:
        "Enter the free competition for a chance to win ₦1,000,000 cash.",
      highlights: [
        "Free entry competition",
        "₦1,000,000 cash prize",
        "No ticket payment required",
        "Transparent winner announcement",
        "Nigeria-wide participation",
      ],
    },
  ];
  
  export const featuredCompetition = competitions[0];
  
  export const winners = [
    {
      name: "Adebayo T.",
      location: "Lagos",
      prize: "Toyota Camry",
      date: "May 2026",
      status: "Published",
    },
    {
      name: "Blessing O.",
      location: "Abuja",
      prize: "₦1,000,000 Cash",
      date: "May 2026",
      status: "Published",
    },
    {
      name: "Chinedu M.",
      location: "Port Harcourt",
      prize: "iPhone 15 Pro",
      date: "April 2026",
      status: "Published",
    },
    {
      name: "Fatima S.",
      location: "Kano",
      prize: "Solar Inverter Package",
      date: "April 2026",
      status: "Published",
    },
  ];
  
  export const userEntries = [
    {
      id: "NW-1001",
      competition: "Win a Toyota Corolla + ₦2,000,000 Cash",
      competitionSlug: "toyota-corolla",
      tickets: ["00124", "00125", "00126"],
      amount: "₦3,000",
      paymentStatus: "Paid",
      entryStatus: "Confirmed",
      drawDate: "30 June 2026",
    },
    {
      id: "NW-1002",
      competition: "Win ₦5,000,000 Cash Prize",
      competitionSlug: "cash-prize",
      tickets: ["00412"],
      amount: "₦500",
      paymentStatus: "Pending",
      entryStatus: "Awaiting Payment",
      drawDate: "15 July 2026",
    },
    {
      id: "NW-1003",
      competition: "Win an iPhone 16 Pro Max + ₦500,000",
      competitionSlug: "iphone-16-pro-max",
      tickets: ["00880", "00881"],
      amount: "₦600",
      paymentStatus: "Paid",
      entryStatus: "Confirmed",
      drawDate: "10 July 2026",
    },
  ];
  
  export const recentOrders = [
    {
      id: "NW-1001",
      customer: "Adebayo T.",
      competition: "Toyota Corolla",
      amount: "₦3,000",
      method: "Bank Transfer",
      status: "Paid",
    },
    {
      id: "NW-1002",
      customer: "Blessing O.",
      competition: "₦5,000,000 Cash",
      amount: "₦500",
      method: "Card",
      status: "Pending",
    },
    {
      id: "NW-1003",
      customer: "Chinedu M.",
      competition: "iPhone 16 Pro Max",
      amount: "₦600",
      method: "USSD",
      status: "Paid",
    },
  ];
  
  export const adminStats = [
    {
      title: "Total Competitions",
      value: "6",
      note: "3 active competitions",
    },
    {
      title: "Total Orders",
      value: "1,248",
      note: "184 pending payments",
    },
    {
      title: "Total Revenue",
      value: "₦4,820,000",
      note: "Sample dashboard value",
    },
    {
      title: "Total Entries",
      value: "12,860",
      note: "Across all competitions",
    },
  ];
  
  export const paymentOptions = [
    {
      title: "Card Payment",
      text: "Pay securely with your debit card through Paystack when payment is activated.",
    },
    {
      title: "Bank Transfer",
      text: "Transfer directly from your bank app to a generated account number when bank transfer is activated.",
    },
    {
      title: "USSD",
      text: "Use your bank USSD code for quick payment when USSD payment is activated.",
    },
  ];